# Generated by Django 3.0.14 on 2021-09-05 09:55

import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(upload_to=blog_app.models.upload_by_name),
        ),
    ]
